/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppFindRouteImport } from './routes/_app.find'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as PresentSlugRouteImport } from './routes/present.$slug'
import { Route as AppSongsSlugRouteImport } from './routes/_app.songs.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppFindRoute = AppFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const PresentSlugRoute = PresentSlugRouteImport.update({
  id: '/present/$slug',
  path: '/present/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSongsSlugRoute = AppSongsSlugRouteImport.update({
  id: '/songs/$slug',
  path: '/songs/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/find': typeof AppFindRoute
  '/planner': typeof AppPlannerRoute
  '/present/$slug': typeof PresentSlugRoute
  '/songs/$slug': typeof AppSongsSlugRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof AppFavoritesRoute
  '/find': typeof AppFindRoute
  '/planner': typeof AppPlannerRoute
  '/present/$slug': typeof PresentSlugRoute
  '/': typeof AppIndexRoute
  '/songs/$slug': typeof AppSongsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/find': typeof AppFindRoute
  '/_app/planner': typeof AppPlannerRoute
  '/present/$slug': typeof PresentSlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/songs/$slug': typeof AppSongsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/find'
    | '/planner'
    | '/present/$slug'
    | '/songs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/find'
    | '/planner'
    | '/present/$slug'
    | '/'
    | '/songs/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/favorites'
    | '/_app/find'
    | '/_app/planner'
    | '/present/$slug'
    | '/_app/'
    | '/_app/songs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PresentSlugRoute: typeof PresentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/find': {
      id: '/_app/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AppFindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/present/$slug': {
      id: '/present/$slug'
      path: '/present/$slug'
      fullPath: '/present/$slug'
      preLoaderRoute: typeof PresentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/songs/$slug': {
      id: '/_app/songs/$slug'
      path: '/songs/$slug'
      fullPath: '/songs/$slug'
      preLoaderRoute: typeof AppSongsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppFindRoute: typeof AppFindRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSongsSlugRoute: typeof AppSongsSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppFindRoute: AppFindRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppIndexRoute: AppIndexRoute,
  AppSongsSlugRoute: AppSongsSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PresentSlugRoute: PresentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
